# Generated by Django 5.2.4 on 2025-11-19 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_classschedule"),
        ("enrollments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("klass", "student")},
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["klass"], name="enrollments_klass_i_55bb7c_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student"], name="enrollments_student_498e45_idx"
            ),
        ),
    ]
