# Generated by Django 5.2.4 on 2025-11-20 00:00

from django.db import migrations, models


def _set_existing_statuses(apps, schema_editor):
    Enrollment = apps.get_model("enrollments", "Enrollment")
    for enrollment in Enrollment.objects.all():
        if enrollment.active:
            enrollment.status = "ACTIVE"
        else:
            enrollment.status = "CANCELLED"
        enrollment.save(update_fields=["status", "active"])


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_classschedule"),
        ("enrollments", "0002_alter_enrollment_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["status"], name="enrollments_status_b2a39f_idx"),
        ),
        migrations.RunPython(_set_existing_statuses, migrations.RunPython.noop),
    ]
