# Generated by Django 5.2.4 on 2025-11-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0003_enrollment_status_and_dates"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="enrollment",
            new_name="enrollments_status_48622c_idx",
            old_name="enrollments_status_b2a39f_idx",
        ),
    ]
