# Generated by Django 5.2.4 on 2025-11-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0006_enrollmentstatuslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Mới"),
                    ("ACTIVE", "Đang học"),
                    ("PAUSED", "Bảo lưu"),
                    ("COMPLETED", "Hoàn tất"),
                    ("CANCELLED", "Nghỉ học"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
