# Generated by Django 5.2.4 on 2025-10-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("CENTER_MANAGER", "Center Manager"),
                    ("STAFF", "Staff"),
                    ("STAFF_SALES", "Sales Staff"),
                    ("TEACHER", "Teacher"),
                    ("ASSISTANT", "Assistant"),
                    ("PARENT", "Parent"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
