# Generated by Django 5.2.4 on 2025-10-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CENTER_MANAGER', 'Center Manager'), ('TEACHER', 'Teacher'), ('ASSISTANT', 'Assistant'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
