# Generated by Django 5.2.4 on 2025-10-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='parentstudentrelation',
            unique_together={('parent', 'student')},
        ),
        migrations.AddIndex(
            model_name='parentstudentrelation',
            index=models.Index(fields=['parent'], name='accounts_pa_parent__8aa009_idx'),
        ),
        migrations.AddIndex(
            model_name='parentstudentrelation',
            index=models.Index(fields=['student'], name='accounts_pa_student_685387_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['center'], name='accounts_us_center__7ed665_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
    ]
