# Generated by Django 5.2.4 on 2025-10-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="STUDENT", max_length=20),
        ),
    ]
