# Generated by Django 5.2.4 on 2025-10-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_role"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_role_1fa9a5_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
