# Generated by Django 5.2.4 on 2025-10-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_user_accounts_us_role_1fa9a5_idx_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("centers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="STUDENT", max_length=20),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="accounts_us_role_1fa9a5_idx"),
        ),
    ]
