# Generated by Django 5.2.4 on 2025-11-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_role_user_accounts_us_role_1fa9a5_idx"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("centers", "0002_center_is_active_alter_room_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCodeCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=5, unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="user_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=10, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_code"], name="accounts_us_user_co_859c4f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="parentstudentrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("student")), _negated=True),
                name="parent_diff_from_student",
            ),
        ),
    ]
