# Generated by Django 5.2.4 on 2025-11-19 08:02

import steam_center.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_usercodecounter_user_user_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=steam_center.storages.MediaStorage(),
                upload_to="avatars/",
            ),
        ),
    ]
