# Generated by Django 5.2.4 on 2025-11-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_discount_and_entry_prices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingentry",
            name="amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Amount in VND (đã trừ giảm giá nếu có)",
                max_digits=12,
            ),
        ),
    ]
