# Generated by Django 5.2.4 on 2025-11-10 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "model_name",
                    models.CharField(
                        db_index=True,
                        help_text="Tên model, ví dụ: 'Class' hoặc 'ClassSession'",
                        max_length=100,
                    ),
                ),
                (
                    "query_params",
                    models.JSONField(
                        default=dict,
                        help_text="Các tham số GET của bộ lọc, lưu dưới dạng JSON",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Những người dùng khác có thể thấy bộ lọc này không?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "name"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "user"],
                        name="filters_sav_model_n_425479_idx",
                    )
                ],
            },
        ),
    ]
