# Generated by Django 5.2.4 on 2025-11-19 08:02

import steam_center.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_studentproduct_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentproduct",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=steam_center.storages.MediaStorage(),
                upload_to="student_products/images/",
            ),
        ),
        migrations.AlterField(
            model_name="studentproduct",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=steam_center.storages.MediaStorage(),
                upload_to="student_products/videos/",
            ),
        ),
    ]
