# Generated by Django 5.2.4 on 2025-11-19 16:22

import steam_center.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_studentproduct_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentexercisesubmission",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=steam_center.storages.MediaStorage(),
                upload_to="exercise_submissions/files/",
            ),
        ),
    ]
