# Generated by Django 5.2.4 on 2025-10-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', 'order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['subject', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('subject', 'order')},
        ),
    ]
