# Generated by Django 5.2.4 on 2025-11-07 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0003_alter_exercise_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="lesson",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise",
                to="curriculum.lesson",
            ),
        ),
    ]
