# Generated by Django 5.2.4 on 2025-11-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0007_module_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="avatar_url",
        ),
        migrations.AddField(
            model_name="module",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="modules/images/",
                verbose_name="Ảnh minh họa",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="subjects/avatars/",
                verbose_name="Ảnh đại diện",
            ),
        ),
    ]
