# Generated by Django 5.2.4 on 2025-11-19 08:02

import steam_center.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "curriculum",
            "0008_remove_module_image_url_remove_subject_avatar_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=steam_center.storages.MediaStorage(),
                upload_to="exercises/",
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=steam_center.storages.MediaStorage(),
                upload_to="lectures/",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=steam_center.storages.MediaStorage(),
                upload_to="modules/images/",
                verbose_name="Ảnh minh họa",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=steam_center.storages.MediaStorage(),
                upload_to="subjects/avatars/",
                verbose_name="Ảnh đại diện",
            ),
        ),
    ]
