# Generated by Django 5.2.4 on 2025-11-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("center", "name")},
        ),
    ]
