# Generated by Django 5.2.4 on 2025-11-19 08:02

import steam_center.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0002_center_is_active_alter_room_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=steam_center.storages.MediaStorage(),
                upload_to="center_avatars/",
            ),
        ),
    ]
