# Generated by Django 5.2.4 on 2025-11-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0003_alter_center_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
