# Generated by Django 5.2.4 on 2025-11-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("class_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="class_sessions.classsession",
            ),
        ),
    ]
