# Generated by Django 5.2.4 on 2025-11-19 04:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_alter_assessment_session"),
        ("class_sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assessment",
            unique_together={("session", "student")},
        ),
    ]
