# Generated by Django 5.2.4 on 2025-11-22 06:24

import django.db.models.deletion
import steam_center.storages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=steam_center.storages.MediaStorage(),
                        upload_to="reward_items/",
                    ),
                ),
                ("cost", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("stock", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PointAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RedemptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("cost_snapshot", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ duyệt"),
                            ("APPROVED", "Đã duyệt"),
                            ("REJECTED", "Từ chối"),
                            ("FULFILLED", "Đã trao"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemption_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemption_requests",
                        to="rewards.rewarditem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RewardTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rewards.rewarditem",
                    ),
                ),
                (
                    "redemption",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="rewards.redemptionrequest",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="redemptionrequest",
            index=models.Index(
                fields=["student"], name="rewards_red_student_a007bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="redemptionrequest",
            index=models.Index(fields=["item"], name="rewards_red_item_id_b93f8f_idx"),
        ),
        migrations.AddIndex(
            model_name="redemptionrequest",
            index=models.Index(fields=["status"], name="rewards_red_status_1358d1_idx"),
        ),
        migrations.AddIndex(
            model_name="redemptionrequest",
            index=models.Index(
                fields=["created_at"], name="rewards_red_created_d9ef42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rewardtransaction",
            index=models.Index(
                fields=["student"], name="rewards_rew_student_3251a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rewardtransaction",
            index=models.Index(
                fields=["created_at"], name="rewards_rew_created_b60c6d_idx"
            ),
        ),
    ]
