# Generated by Django 5.2.4 on 2025-11-19 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rewardtransaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="rewardtransaction",
            index=models.Index(
                fields=["student"], name="rewards_rew_student_3251a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rewardtransaction",
            index=models.Index(
                fields=["created_at"], name="rewards_rew_created_b60c6d_idx"
            ),
        ),
    ]
