# Generated by Django 5.2.4 on 2025-11-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0003_session_point_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sessionpointevent",
            new_name="rewards_ses_student_9c999a_idx",
            old_name="rewards_ses_student_02cacb_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionpointevent",
            new_name="rewards_ses_session_9fb00a_idx",
            old_name="rewards_ses_session_9b7fa5_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionpointevent",
            new_name="rewards_ses_event_t_d9af09_idx",
            old_name="rewards_ses_event_t_56a512_idx",
        ),
    ]
