# Generated by Django 5.2.4 on 2025-11-10 17:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_alter_assessment_session"),
        ("attendance", "0002_alter_attendance_session"),
        ("classes", "0001_initial"),
        ("students", "0002_alter_studentproduct_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classassistant",
            unique_together={("klass", "assistant", "scope")},
        ),
        migrations.DeleteModel(
            name="ClassSession",
        ),
    ]
