# Generated by Django 5.2.4 on 2025-11-11 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_classassistant_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Thứ Hai"),
                            (1, "Thứ Ba"),
                            (2, "Thứ Tư"),
                            (3, "Thứ Năm"),
                            (4, "Thứ Sáu"),
                            (5, "Thứ Bảy"),
                            (6, "Chủ Nhật"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "klass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_schedules",
                        to="classes.class",
                    ),
                ),
            ],
            options={
                "ordering": ["klass", "day_of_week", "start_time"],
                "unique_together": {("klass", "day_of_week", "start_time")},
            },
        ),
    ]
