# Generated by Django 5.2.4 on 2025-11-19 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_session"),
        ("class_sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-session__date", "student__username"]},
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("session", "student")},
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["session"], name="attendance__session_ad8f43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student"], name="attendance__student_018d17_idx"
            ),
        ),
    ]
